src/Entity/Person.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PersonRepository")
 */
class Person
{
    /**
     * @var int
     * 
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;
    
    /**
     * par défaut, le champ est un varchar(255) NOT NULL
     * @var string
     * @ORM\Column()
     */
    private $firstname;
    
     /**
     * @var string
     * @ORM\Column()
     */
    private $lastname;
    
     /**
     * @var string
     * @ORM\Column(unique=true)
     */
    private $email;
    
     /**
     * @var \Datetime
     * @ORM\Column(type="date")
     */
    private $birthdate;
    
    public function getId() 
    {
        return $this->id;
    }
    
    public function getFirstname() {
        return $this->firstname;
    }

    public function getLastname() {
        return $this->lastname;
    }

    public function getEmail() {
        return $this->email;
    }

    public function getBirthdate(): \Datetime {
        return $this->birthdate;
    }

    public function setFirstname($firstname) {
        $this->firstname = $firstname;
        return $this;
    }

    public function setLastname($lastname) {
        $this->lastname = $lastname;
        return $this;
    }

    public function setEmail($email) {
        $this->email = $email;
        return $this;
    }

    public function setBirthdate(Datetime $birthdate) {
        $this->birthdate = $birthdate;
        return $this;
    }

    //ajout d'une méthode apres LES SETTERS/GETTERS
    public function getFullname() {
        return $this->firstname.' '.$this->lastname ;
    }   
}

src/Controller/PersonController.php
<?php

namespace App\Controller;

use App\Entity\Person;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use function dump;

/**
     * @Route("/person")
     */

class PersonController extends Controller
{
    /**
     * //Le chemin complet de la route est /person/list
     * @Route("/list")
     */
    public function index()
    {
        //récupérartion de l'entity manager // gestionnaire d'entités de Doctrine
        $em = $this->getDoctrine()->getManager();
        dump(Person::class);
        $personRepository = $em->getRepository(Person::class);
        
        //select * sur la table Person - ne renvoit pas comme pdo un tableau, mais un tableau d'objets person (3 instances
        $persons = $personRepository->findAll();
        
        dump($persons);
        return $this->render('person/index.html.twig', 
            [
            'persons' => $persons
        ]);
    }
    
     /**
     * L'id doit être un nombre (\d+ en expression regex)
     * @Route("/{id}",requirements={"id":"\d+"}) //annotation
     * @param int $id //commentaire de documentation
     */
    public function detail($id)
    {
        //ns reprenons les 2 lignes de la méthode précédente
        $em = $this->getDoctrine()->getManager();
        $personRepository = $em->getRepository(Person::class);
        
        //méthode find()-retourne un objet Person par la clé primaire
        //ou null si absence de résultat
        $person = $personRepository->find($id);
        
        //exception - s'il n'y a pas de personne avec l'id reçu dans l'url
        // on jette une 404
        if(is_null($person)) {
            throw new NotFoundHttpException();
        }
        
        //si pas null, on passe à la vue
        return $this->render('person/detail.html.twig', 
        [
            'person' => $person
        ]);        
    }
    
    /**
     * @Route("/search") //annotation
     * 
     */
    public function search(Request $request)
    {
        $person = null; //pour éviter d'avoir un undefined variable à l'affichage page
        
        if($request->isMethod('POST')){
            $em = $this->getDoctrine()->getManager();
            $personRepository = $em->getRepository(Person::class);
        
            $person = $personRepository->findOneBy([ // renvoie 1 ou 0 résultat
                'email' => $request->request->get('email')
            ]); //on pourait rajouter d'autres champs et la clause va être construite en adéquation
        }
        
        return $this->render('person/search.html.twig', 
        [
            'person' => $person
        ]);        
    }
        /**
        * @Route("/search/lastname") 
        */
        public function searchByLastname(Request $request)
    {
        $persons = []; //il peut y avoir des noms égaux
        
        if($request->isMethod('POST')){
            $em = $this->getDoctrine()->getManager();
            $personRepository = $em->getRepository(Person::class);
        
            $persons = $personRepository->findBy([ // renvoie 1 ou 0 résultat
                'lastname' => $request->request->get('lastname')
            ]); 
        }
        
        return $this->render('person/search_by_lastname.html.twig', 
        [
            'persons' => $persons
        ]);        
    }
    
}

templates/person/detail.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <strong>Nom : </strong>{{ person.lastname }}<br>
    <strong>Email : </strong>{{ person.email }}<br>
    <strong>Date de naissance : </strong>{{ person.birthdate|date('d/m/Y') }}
{% endblock %}

templates/person/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <table border="1px">
        <tr>
            <th>Id</th>
            <th>Prénom</th>
            <th>Nom</th>
            <th>Prénom et nom</th>
            <th>Email</th>
            <th>Date de naissance</th>
        </tr>
       
        {% for person in persons %}
            <tr>
                <td><a href="{{ path('app_person_detail',{id: person.id }) }}">{{ person.id }}</a></td>
                <td>{{person.firstname }}</td>
                <td>{{person.lastname }}</td>
                {# ligne ci-dessous utilisation de la méthode créée manuellement 
                dans le fihcier Person.php lg 89 #}
                <td>{{person.fullname }}</td> 
                <td>{{person.email }}</td>
                <td>{{person.birthdate|date('d/m/Y') }}</td>                
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/person/search.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <form method=post">
        <label>Email : </label>
        <input type="text" name="email">
        <button type="submit">Rechercher</button>
    </form>
    
    {% if person is not null %}
        <strong>Nom : </strong>{{ person.lastname }}<br>
        <strong>Email : </strong>{{ person.email }}<br>
        <strong>Date de naissance : </strong>{{ person.birthdate|date('d/m/Y') }}
    {% endif %}
{% endblock %}

templates/person/search_by_lastname.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <form method="post">
        <label>Nom : </label>
        <input type="text" name="lastname">
        <button type="submit">Rechercher par nom</button>
    </form>
    
    <table border="1px">
            <tr>
                <th>Id</th>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Prénom et nom</th>
                <th>Email</th>
                <th>Date de naissance</th>
            </tr>

            {% for person in persons %}
                <tr>
                    <td><a href="{{ path('app_person_detail',{id: person.id }) }}">{{ person.id }}</a></td>
                    <td>{{person.firstname }}</td>
                    <td>{{person.lastname }}</td>
                    {# ligne ci-dessous utilisation de la méthode créée manuellement 
                    dans le fihcier Person.php lg 89 #}
                    <td>{{person.fullname }}</td> 
                    <td>{{person.email }}</td>
                    <td>{{person.birthdate|date('d/m/Y') }}</td>                
                </tr>
            {% else %}
                <tr>
                    <td colspan="6">Aucun résultat</td>
                </tr>
            {% endfor %}
        </table>
{% endblock %}